---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.userdetails
    config:
        locations:
            - file:/data/userdetails/config/userdetails-config.properties
            - file:/data/userdetails/config/userdetails-config.yml
            - file:/data/userdetails/config/userdetails-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugins:
        twitterbootstrap:
            fixtaglib: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    data:
      redis:
        repositories:
          enabled: false
    session:
        store-type: none # Spring Session support disabled by default.
        disable-redis-config-action: false
        grails:
            mutableAttributes:
              - SYNCHRONIZER_TOKENS_HOLDER
server:
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for
    port-header: x-forwarded-port
    protocol_header: x-forwarded-proto
    protocol-header-https-value: https
    # Add IPv6 localhost to default list
    internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1
---
grails:
    mime:
        use:
            accept:
                header: true
        disable:
            accept:
                header:
                    userAgents: []
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    databinding:
        convertEmptyStringsToNull: false
    cache:
        enabled: true
        ehcache:
            cacheManagerName: 'userdetails-cache-manager'
            ehcacheXmlLocation: 'classpath:userdetails-ehcache.xml'
            reloadable: false

security:
    cas:
        uriFilterPattern: '/admin/.*,/registration/editAccount,/my-profile,/my-profile/,/myprofile/,/myprofile,/profile/.*,/admin/,/admin,/registration/update,/registration/update/.*,/monitoring,/monitoring/*,/registration/disableAccount/.*,/registration/disableAccount,/admin/admin/downloadUsersCsvFile,/alaAdmin.*'
        authenticateOnlyIfLoggedInFilterPattern: '/'
    filterOrder: 0
    basic:
        enabled: true
        authorizeMode: role
        realm: ALA User Details
        path:
          - /status/**
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    sensitive: true
    jmx:
        enabled: true
        unique-names: true
    cors:
        allow-credentials: true
        allowed-methods:
          - GET
          - POST
          - DELETE
          - PUT
        allowed-headers: "*"
        allowed-origins: "*"
management:
    context-path: /status
    security:
        enabled: true
        roles:
          - ACTUATOR
    health:
      redis:
        enabled: false # set to true for HA environments
spring:
    boot:
        admin:
            client:
                enabled: false
                service-base-url: ${serverURL}
                metadata:
                    user:
                        name: ${security.user.name}
                        password: ${security.user.password}

password:
    encoder: bcrypt # or legacy
bcrypt:
    strength: 10

attributes:
    states:
        path: classpath:states.json

skin:
    layout: "ala-main"
    fluidLayout: false
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"
privacyPolicy: "https://www.ala.org.au/privacy-policy/"
termsOfUse: "https://www.ala.org.au/terms-of-use/"

oauth:
#  debug: true
  providers:
    flickr:
      enabled: true
      api: 'com.github.scribejava.apis.FlickrApi'
      key: "xxxxxxxxxxxxxxxxxxxxx"
      secret: "xxxxxxxxxxxxxxxxxxxxx"
      successUri: '/profile/flickrSuccess'
      failureUri: '/profile/flickrFail'
      callback: "xxxxxxxxxxxxx/yyyyyyyyyy/profile/flickrCallback"
    inaturalist:
      enabled: false
      api: 'au.org.ala.oauth.apis.InaturalistApi'
      key: 'xxxxxxxxxxxxxxxxxxxxx'
      secret: 'xxxxxxxxxxxxxxxxxxxxx'
      successUri: '/profile/inaturalistSuccess'
      failureUri: '/profile/inaturalistFailure'
      callback: 'xxxxxx/yyyyyyy/profile/inaturalistCallback'

inaturalist:
  name: iNaturalist Australia
  baseUrl: https://inaturalist.ala.org.au/
  searchQuery: data_resource_uid:dr1411
  sightingsSearchQuery: data_resource_uid:dr364

biocache:
  search:
    baseUrl: https://biocache.ala.org.au/occurrences/search

markdown:
    removeHtml: true

recaptcha:
  baseUrl: https://www.google.com/recaptcha/api/
  siteKey: 
  secretKey:

environments:
    development:
        grails:
            serverURL: "http://devt.ala.org.au:8080/userdetails"
            mail:
                host: "localhost"
                port: 1025
                username: postie.emailSender
        security:
            cas:
                appServerName: "http://devt.ala.org.au:8080"
    test:
        security:
            cas:
                appServerName: "http://auth.ala.org.au"
    production:
        grails:
            serverURL: "http://auth.ala.org.au/userdetails"
            mail:
                host: "localhost"
                port: 25
        security:
            cas:
                appServerName: "http://auth.ala.org.au"

---
hibernate:
    show_sql: false
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: true
#        region:
#            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    type: "com.zaxxer.hikari.HikariDataSource"
    username:
    password:
    properties:
#        # http://www.grails.org/doc/latest/guide/single.html#dataSource
#        # see http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes for more
#        timeBetweenEvictionRunsMillis: 60000 # milliseconds (default: 5000)
#        testOnBorrow: true # default: false
#        testOnReturn: false # default: false
#        testWhileIdle: true # default: false
#        validationQuery: "SELECT 1" # default: null
#        validationQueryTimeout: 10 # seconds (default: -1 i.e. disabled)
#        validationInterval: 30000 # milliseconds, default is 30000 (30 seconds)
#        removeAbandoned: true # # default: false
#        removeAbandonedTimeout: 300 # seconds (default: 60)
#        logAbandoned: true # adds some overhead to every borrow from the pool, disable if it becomes a performance issue
#        logValidationErrors: true # default: false, logs validation errors at SEVERE
#        # NOTE: removeAbandoned: true OR testWhileIdle: true enables the Pool Cleaner. There is a bug with the
#        # pool cleaner which causes deadlocks when using older mysql jdbc drivers. This configuration has been
#        # tested successfully with mysql:mysql-connector-java:5.1.34.
#        # mysql jdbc connection properties - see http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
#        dbProperties:
#            autoReconnect: true
#            connectTimeout: 0
#            useUnicode: true
#            characterEncoding: "UTF-8"

environments:
    development:
        dataSource:
            dbCreate: "validate"
            url: "jdbc:mysql://localhost/emmet"
            username: "root"
            password: "password"
    test:
        dataSource:
            dbCreate: "create-drop"
            pooled: true
            driverClassName: "org.h2.Driver"
            username: "sa"
            password: ""
    production:
        dataSource:
            dbCreate: "validate"
---
spring:
    profiles: disable-redis
#    autoconfigure:
#        exclude:
#        - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
#        - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
#    data:
#        redis:
#            repositories:
#                enabled: false